(function(root){'use strict';
 const TH={TOTAL:{meta:40,crit:60},D1D3:{meta:35,crit:55},D4D10:{meta:40,crit:60}};
 const PAL=['#1C1C74','#4343B5','#9192DC','#CDCFDD','#A9ACC2','#F29AA2','#E0293B','#9E0B1C'];
 function th(g){return TH[g]||TH.TOTAL;}
 function breaks(g){const t=th(g),m=t.meta,k=t.crit;return [0,Math.max(5,m-20),m-10,m,(m+k)/2,k,k+10,k+20,100];}
 function level(pc,g){const t=th(g);return pc>t.crit?'crit':pc<=t.meta?'ok':'warn';}
 function color(pc,g){if(!Number.isFinite(pc))return '#DADBE6';const b=breaks(g);for(let i=7;i>=0;i--)if(pc>=b[i])return PAL[i];return PAL[0];}
 const LBL={ok:'Alto',warn:'Moderado',crit:'Bajo'};
 function chip(pc,g){const l=level(pc,g);return '<span class="st '+l+'">'+LBL[l]+'</span>';}
 function vigColor(pc){if(!Number.isFinite(pc))return '#DADBE6';const f=Math.max(0,Math.min(1,pc/100)),a=[237,237,249],b=[45,45,147];return 'rgb('+a.map((v,i)=>Math.round(v+(b[i]-v)*f)).join(',')+')';}
 function legend(g,indicator){if(indicator==='vig')return '<span class="leg-t">% vigencia</span><span>0 %</span><span style="display:inline-block;width:150px;height:10px;background:linear-gradient(to right,#EDEDF9,#2D2D93)"></span><span>100 %</span><span class="leg-i"><i style="background:#DADBE6"></i>Sin datos</span>';const b=breaks(g);return '<span class="leg-t">% caducidad</span>'+PAL.map((c,i)=>'<span class="leg-i"><i style="background:'+c+'"></i>'+(i===7?'≥ '+b[i]:b[i]+'–'+b[i+1])+'</span>').join('')+'<span class="leg-i"><i style="background:#DADBE6"></i>Sin datos</span><span class="leg-n">Caducidad baja ≤ '+th(g).meta+' % · Caducidad alta &gt; '+th(g).crit+' %</span>';}
 root.RSStatus={th,level,color,vigColor,chip,legend,PAL};
const N=new Intl.NumberFormat('de-DE'),P=new Intl.NumberFormat('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const number=v=>Number.isFinite(v)?N.format(v):'No disponible',pct=v=>Number.isFinite(v)?P.format(v)+' %':'No disponible';
 function tooltip(event,html){const el=document.getElementById('tooltip');el.innerHTML=html;el.hidden=false;const box=el.getBoundingClientRect();el.style.left=Math.max(8,Math.min(event.clientX+15,innerWidth-box.width-10))+'px';el.style.top=Math.max(8,Math.min(event.clientY+15,innerHeight-box.height-10))+'px';}function hide(){document.getElementById('tooltip').hidden=true;}function detail(r){return '<span>'+esc(r.province)+'</span><strong>'+esc(r.name)+'</strong><dl>'+[['Total núcleos',number(r.total)],['Vigentes',number(r.vig)],['Caducados',number(r.cad)],['% Vigencia',pct(r.pctVig)],['% Caducidad',pct(r.pctCad)]].map(([a,b])=>'<dt>'+a+'</dt><dd>'+b+'</dd>').join('')+'</dl>';}
 function wire(container,rows){container.querySelectorAll('[data-tip]').forEach(el=>{const r=rows[Number(el.dataset.tip)];el.addEventListener('pointermove',e=>tooltip(e,detail(r)));el.addEventListener('pointerleave',hide);el.addEventListener('focus',()=>{const b=el.getBoundingClientRect();tooltip({clientX:b.left,clientY:b.top},detail(r));});el.addEventListener('blur',hide);});}
 function render(rows,s,state){const field=state.indicator==='vig'?'pctVig':'pctCad',label=state.indicator==='vig'?'vigencia':'caducidad',color=state.indicator==='vig'?'#2D2D93':'#A3A6C2';document.getElementById('rankingTitle').textContent=(rows.length===1?'Detalle del cantón':'Cantones con mayor '+label);document.getElementById('topLabel').textContent=rows.length===1?'1 CANTÓN':'TOP '+Math.min(10,rows.length);const ranking=document.getElementById('ranking'),rank=[...rows].sort((a,b)=>b[field]-a[field]||b.total-a.total||a.id.localeCompare(b.id)).slice(0,10);ranking.innerHTML=rank.map((r,i)=>'<div class="rank-row" tabindex="0" data-tip="'+i+'"><span class="position">'+(rows.length===1?'—':String(i+1).padStart(2,'0'))+'</span><div><strong>'+esc(r.name)+'</strong><small>'+esc(r.province)+' · '+number(r.total)+' núcleos</small><div class="track"><i style="width:'+r[field]+'%;background:'+RSStatus.color(r.pctCad,state.group)+'"></i></div></div><span class="value lv-'+RSStatus.level(r.pctCad,state.group)+'">'+pct(r[field])+'</span></div>').join('')||'<p class="empty">Sin registros para esta selección.</p>';wire(ranking,rank);
 const comparison=document.getElementById('comparison'),fraction=s.total?s.vig/s.total:0,circ=2*Math.PI*74;comparison.innerHTML='<svg viewBox="0 0 240 220" role="img" aria-label="Vigentes '+pct(s.pctVig)+', Caducados '+pct(s.pctCad)+'"><circle cx="120" cy="104" r="74" fill="none" stroke="#EEEEF5" stroke-width="21"/><circle tabindex="0" data-status="cad" cx="120" cy="104" r="74" fill="none" stroke="#A3A6C2" stroke-width="21" stroke-dasharray="'+circ*(1-fraction)+' '+circ+'" stroke-dashoffset="'+(-circ*fraction)+'" transform="rotate(-90 120 104)"/><circle tabindex="0" data-status="vig" cx="120" cy="104" r="74" fill="none" stroke="#2D2D93" stroke-width="21" stroke-dasharray="'+circ*fraction+' '+circ+'" transform="rotate(-90 120 104)"/><text x="120" y="100" text-anchor="middle" fill="#1A1A3A" font-size="25" font-weight="600">'+pct(s.pctVig)+'</text><text x="120" y="123" text-anchor="middle" fill="#71718E" font-size="11">VIGENCIA</text></svg><div class="compare-values"><div class="vig"><span>● Vigentes</span><strong>'+number(s.vig)+'</strong><small>'+pct(s.pctVig)+'</small></div><div class="cad"><span>● Caducados</span><strong>'+number(s.cad)+'</strong><small>'+pct(s.pctCad)+'</small></div></div>';comparison.querySelectorAll('[data-status]').forEach(el=>{const show=e=>tooltip(e,'<strong>'+(el.dataset.status==='vig'?'Vigentes':'Caducados')+'</strong>'+number(s[el.dataset.status])+' núcleos · '+pct(s[el.dataset.status==='vig'?'pctVig':'pctCad']));el.addEventListener('pointermove',show);el.addEventListener('pointerleave',hide);el.addEventListener('focus',()=>{const b=el.getBoundingClientRect();show({clientX:b.left,clientY:b.top});});el.addEventListener('blur',hide);});
 const grouped=new Map();rows.forEach(r=>{const key=state.province||state.canton?r.id:r.province;if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(r);});const dist=[...grouped.values()].map(rr=>({...root.RSData.aggregate(rr),name:state.province||state.canton?rr[0].name:rr[0].province,province:rr[0].province})).sort((a,b)=>b.total-a.total);const max=Math.max(1,...dist.map(r=>r.total));document.getElementById('distributionTitle').textContent=state.canton?'Composición del cantón':state.province?'Comparación por cantón':'Comparación por provincia';const el=document.getElementById('distribution');el.innerHTML=dist.map((r,i)=>'<div class="dist-row" tabindex="0" data-tip="'+i+'"><div class="dist-label"><span>'+esc(r.name)+(RSStatus.level(r.pctCad,state.group)==='crit'?' <b class="lv-crit">▲ '+pct(r.pctCad)+'</b>':'')+'</span><strong>'+number(r.total)+'</strong></div><div class="stack" style="width:'+100*r.total/max+'%"><span class="vig" style="width:'+r.pctVig+'%"></span><span class="cad" style="width:'+r.pctCad+'%"></span></div></div>').join('');wire(el,dist);
 }
 root.RSCharts={render,number,pct,esc,tooltip,hide,detail};
})(globalThis);
