(function(root){
 'use strict';
 const groups={TOTAL:{label:'TOTAL',cols:['toth_rs','toth_rs_vig','toth_rs_cad','pct_rs_vig','pct_rs_cad']},D1D3:{label:'D1-D3 · 3 años',cols:['toth_d1d3','toth_d1d3_vig','toth_d1d3_cad','pct_d1d3_vig','pct_d1d3_cad']},D4D10:{label:'D4-D10 · 5 años',cols:['toth_d4d10','toth_d4d10_vig','toth_d4d10_cad','pct_d4d10_vig','pct_d4d10_cad']}};
 function parseCSV(text){let rows=[],row=[],value='',quoted=false;text=text.replace(/^\uFEFF/,'');for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(value);value='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(v=>v!==''))rows.push(row);row=[];value='';}else value+=ch;}if(value||row.length){row.push(value);rows.push(row);}if(quoted)throw Error('CSV con comillas sin cerrar');const headers=rows.shift();return rows.map(r=>{if(r.length!==headers.length)throw Error('CSV con número de columnas inválido');return Object.fromEntries(headers.map((h,i)=>[h,r[i]]));});}
 function load(sources){const raw=parseCSV(sources.datos),provinces=parseCSV(sources.provincias),cantons=parseCSV(sources.cantones),issues=[];const cm=new Map(),pm=new Map();function index(rows,key,map){for(const r of rows){if(map.has(r[key]))issues.push('Código duplicado en catálogo: '+r[key]);map.set(r[key],r);}}index(cantons,'canton',cm);index(provinces,'provincia',pm);const seen=new Set();for(const r of raw){const id=r.canton+' '+r.nom_can;if(seen.has(r.canton))issues.push(id+': código duplicado');seen.add(r.canton);for(const [g,{cols}]of Object.entries(groups)){for(const col of cols){r[col]=r[col]===''||r[col]===undefined?NaN:Number(r[col]);if(!Number.isFinite(r[col]))issues.push(id+' / '+g+': valor inválido en '+col);}const [t,v,c,pv,pc]=cols.map(k=>r[k]);if([t,v,c].some(x=>!Number.isSafeInteger(x)||x<0))issues.push(id+' / '+g+': conteo inválido');if(t!==v+c)issues.push(id+' / '+g+': Total != Vigentes + Caducados');if([pv,pc].some(x=>x<0||x>100))issues.push(id+' / '+g+': porcentaje fuera de 0–100');if(t>0&&(Math.abs(pv-100*v/t)>.00500001||Math.abs(pc-100*c/t)>.00500001))issues.push(id+' / '+g+': porcentaje no concuerda con los conteos');}for(const suffix of ['','_vig','_cad'])if(r['toth_rs'+suffix]!==r['toth_d1d3'+suffix]+r['toth_d4d10'+suffix])issues.push(id+': grupos no reconcilian '+suffix);const geo=cm.get(r.canton),prov=pm.get(r.canton.slice(0,2));if(!geo||!prov)issues.push(id+': falta enlace territorial');else if(geo.nom_can!==r.nom_can||prov.nom_pro!==r.nom_pro)issues.push(id+': nombres territoriales diferentes');r.lat=geo&&geo.latitud_canton!==''?Number(geo.latitud_canton):NaN;r.lon=geo&&geo.longitud_canton!==''?Number(geo.longitud_canton):NaN;if(!Number.isFinite(r.lat)||!Number.isFinite(r.lon)||Math.abs(r.lat)>90||Math.abs(r.lon)>180)issues.push(id+': coordenadas inválidas');if(!/^\d{4}-\d{2}-\d{2}$/.test(r.fecha_corte))issues.push(id+': fecha inválida');}
 if(issues.length)console.error('Inconsistencias del Registro Social',issues);return {raw,provinces,cantons,issues,dates:[...new Set(raw.map(r=>r.fecha_corte))]};}
 function project(r,group){const [t,v,c,pv,pc]=groups[group].cols;return {id:r.canton,province:r.nom_pro,name:r.nom_can,total:r[t],vig:r[v],cad:r[c],pctVig:r[pv],pctCad:r[pc],lat:r.lat,lon:r.lon};}
 function aggregate(rows){const out=rows.reduce((a,r)=>({total:a.total+r.total,vig:a.vig+r.vig,cad:a.cad+r.cad}),{total:0,vig:0,cad:0});return {...out,pctVig:out.total?100*out.vig/out.total:null,pctCad:out.total?100*out.cad/out.total:null};}
 function view(data,state){const rows=data.raw.filter(r=>(!state.province||r.nom_pro===state.province)&&(!state.canton||r.canton===state.canton)).map(r=>({...project(r,state.group),...(data.temporal?data.temporal.status(r.canton,state.group,state.fechaAnalisis||r.fecha_corte):{})}));return {rows,summary:aggregate(rows)};}
 root.RSData={groups,parseCSV,load,project,aggregate,view};
})(globalThis);
