(function(root){
 'use strict';
 function build(data,catalogText,temporalText){
  const catalog=RSData.parseCSV(catalogText),byId=new Map(),buckets=new Map(),cantonBuckets=new Map(),issues=[],seen=new Set();let count=0;
  const cantonNames=new Map(data.raw.map(r=>[r.canton,r]));
  for(const r of catalog){const c=cantonNames.get(r.parroquia.slice(0,4));if(byId.has(r.parroquia))issues.push(r.parroquia+': parroquia duplicada');const lat=Number(r.latitud_parroquia),lon=Number(r.longitud_parroquia);if(!c||r.latitud_parroquia===''||r.longitud_parroquia===''||!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)issues.push(r.parroquia+': catálogo o coordenadas inválidos');byId.set(r.parroquia,{id:r.parroquia,name:r.nom_par,province:c?.nom_pro,canton:c?.canton,cantonName:c?.nom_can,lat,lon});}
  for(const r of RSData.parseCSV(temporalText)){count++;const p=byId.get(r.parroquia),key=r.parroquia+'|'+r.grupo,unique=key+'|'+r.fecha_vencimiento,n=Number(r.nucleos),date=new Date(r.fecha_vencimiento+'T12:00:00Z');if(!p||p.canton!==r.canton||p.province!==r.nom_pro||p.cantonName!==r.nom_can)issues.push(r.parroquia+': enlace parroquial inconsistente');if(!['D1-D3','D4-D10'].includes(r.grupo)||r.nucleos===''||!Number.isSafeInteger(n)||n<0||!/^\d{4}-\d{2}-\d{2}$/.test(r.fecha_vencimiento)||!Number.isFinite(date.getTime())||date.toISOString().slice(0,10)!==r.fecha_vencimiento){issues.push(r.parroquia+': registro temporal inválido');continue;}if(seen.has(unique))issues.push(r.parroquia+': fecha/grupo duplicados');seen.add(unique);if(!buckets.has(key))buckets.set(key,new Map());const b=buckets.get(key);b.set(r.fecha_vencimiento,(b.get(r.fecha_vencimiento)||0)+n);const ck=r.canton+'|'+r.grupo;if(!cantonBuckets.has(ck))cantonBuckets.set(ck,new Map());const cb=cantonBuckets.get(ck);cb.set(r.fecha_vencimiento,(cb.get(r.fecha_vencimiento)||0)+n);}
  for(const [key,original]of data.temporal.index){const aggregate=cantonBuckets.get(key);let previous=0;original.dates.forEach((date,i)=>{const n=original.cumulative[i]-previous;previous=original.cumulative[i];if(!aggregate||aggregate.get(date)!==n)issues.push(key+' / '+date+': parroquias no reconcilian con cantón');});if(aggregate&&aggregate.size!==original.dates.length)issues.push(key+': fechas adicionales en parroquias');}
  for(const key of cantonBuckets.keys())if(!data.temporal.index.has(key))issues.push(key+': cantón/grupo sin referencia');
  for(const [key,b]of buckets){let total=0;const pairs=[...b].sort((a,b)=>a[0].localeCompare(b[0]));buckets.set(key,{dates:pairs.map(p=>p[0]),cumulative:pairs.map(p=>total+=p[1]),total});}
  for(const id of byId.keys())if(!buckets.has(id+'|D1-D3')&&!buckets.has(id+'|D4-D10'))issues.push(id+': parroquia sin datos temporales');
  function status(id,group,date){let total=0,cad=0;for(const label of group==='TOTAL'?['D1-D3','D4-D10']:[group==='D1D3'?'D1-D3':'D4-D10']){const b=buckets.get(id+'|'+label);if(!b)continue;let lo=0,hi=b.dates.length;while(lo<hi){const mid=(lo+hi)>>1;if(b.dates[mid]<date)lo=mid+1;else hi=mid;}total+=b.total;cad+=lo?b.cumulative[lo-1]:0;}return {total,cad,vig:total-cad,pctVig:total?100*(total-cad)/total:null,pctCad:total?100*cad/total:null};}
  data.parish={catalog:byId,index:buckets,status,recordCount:count};data.issues.push(...issues);if(issues.length)console.error('Inconsistencias parroquiales',issues);return data.parish;
 }
 function view(data,state){return [...data.parish.catalog.values()].filter(p=>(!state.province||p.province===state.province)&&(!state.canton||p.canton===state.canton)).map(p=>({...p,...data.parish.status(p.id,state.group,state.fechaAnalisis)}));}
 root.RSParish={build,view};
})(globalThis);
