(function(root){
 'use strict';
 const start='2020-12-01',end='2031-09-30';
 const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
 const today=()=>iso(new Date());
 const format=date=>new Intl.DateTimeFormat('es-EC',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z'));
 function close(index){const year=2020+Math.floor((11+index)/12),month=(11+index)%12;return iso(new Date(year,month+1,0,12));}
 function monthIndex(date){return (Number(date.slice(0,4))-2020)*12+Number(date.slice(5,7))-12;}
 function move(date,delta){const [y,m,d]=date.split('-').map(Number);const destination=new Date(y,m-1+delta,1,12);const last=new Date(destination.getFullYear(),destination.getMonth()+1,0,12).getDate();destination.setDate(Math.min(d,last));const value=iso(destination);return value<start?start:value>end?end:value;}
 function build(data,text){const index=new Map(),issues=[],seen=new Set();let recordCount=0;const known=new Map(data.raw.map(r=>[r.canton,r]));
 for(const r of RSData.parseCSV(text)){recordCount++;const id=r.canton,key=id+'|'+r.grupo,source=known.get(id);const count=Number(r.nucleos);const date=r.fecha_vencimiento;const parsedDate=new Date(date+'T12:00:00Z');const validDate=/^\d{4}-\d{2}-\d{2}$/.test(date)&&Number.isFinite(parsedDate.getTime())&&parsedDate.toISOString().slice(0,10)===date;
 if(!source||source.nom_pro!==r.nom_pro||source.nom_can!==r.nom_can)issues.push(id+': enlace temporal inválido');
 if(!['D1-D3','D4-D10'].includes(r.grupo)||r.nucleos===''||!Number.isSafeInteger(count)||count<0||!validDate){issues.push(id+': registro temporal inválido '+date);continue;}
 const unique=key+'|'+date;if(seen.has(unique))issues.push(id+': vencimiento duplicado '+r.grupo+' '+date);seen.add(unique);
 if(!index.has(key))index.set(key,new Map());const bucket=index.get(key);bucket.set(date,(bucket.get(date)||0)+count);}
 for(const [key,bucket]of index){const ordered=[...bucket].sort((a,b)=>a[0].localeCompare(b[0]));let total=0;index.set(key,{dates:ordered.map(([date])=>date),cumulative:ordered.map(([,v])=>total+=v),total});}
 function status(id,group,date){const g=group==='D1D3'?'D1-D3':'D4-D10';const buckets=group==='TOTAL'?['D1-D3','D4-D10']:[g];let total=0,cad=0;for(const label of buckets){const b=index.get(id+'|'+label);if(!b)continue;let lo=0,hi=b.dates.length;while(lo<hi){const mid=(lo+hi)>>1;if(b.dates[mid]<date)lo=mid+1;else hi=mid;}total+=b.total;cad+=lo?b.cumulative[lo-1]:0;}const vig=total-cad;return {total,vig,cad,pctVig:total?100*vig/total:null,pctCad:total?100*cad/total:null};}
 for(const r of data.raw)for(const [group,{cols}]of Object.entries(RSData.groups)){const value=status(r.canton,group,r.fecha_corte);if(value.total!==r[cols[0]]||value.vig!==r[cols[1]]||value.cad!==r[cols[2]])issues.push(r.canton+' / '+group+': datos temporales no reproducen el corte');}
 if(issues.length)console.error('Inconsistencias temporales',issues);data.issues.push(...issues);data.temporal={status,index,recordCount};return data.temporal;}
 let cachedKey='',cachedSeries=[];
 function series(data,state){const key=[state.group,state.province,state.canton].join('|');if(key===cachedKey)return cachedSeries;const ids=data.raw.filter(r=>(!state.province||r.nom_pro===state.province)&&(!state.canton||r.canton===state.canton)).map(r=>r.canton);cachedSeries=Array.from({length:130},(_,i)=>{const date=close(i),sum=RSData.aggregate(ids.map(id=>data.temporal.status(id,state.group,date)));return {date,...sum};});cachedKey=key;return cachedSeries;}
 function init(){document.getElementById('previousMonth').onclick=()=>RSState.set({fechaAnalisis:move(RSState.get().fechaAnalisis,-1)});document.getElementById('nextMonth').onclick=()=>RSState.set({fechaAnalisis:move(RSState.get().fechaAnalisis,1)});document.getElementById('todayButton').onclick=()=>RSState.set({fechaAnalisis:today()});document.getElementById('timeSlider').oninput=e=>RSState.set({fechaAnalisis:close(Number(e.target.value))});}
 function controls(state){const now=today(),selected=state.fechaAnalisis,slider=document.getElementById('timeSlider');slider.value=Math.max(0,Math.min(129,monthIndex(selected)));slider.setAttribute('aria-valuetext',format(selected));document.getElementById('analysisDate').textContent=format(selected);const badge=document.getElementById('todayBadge');badge.hidden=selected!==now;document.getElementById('todayButton').classList.toggle('selected',selected===now);document.getElementById('previousMonth').disabled=selected<=start;document.getElementById('nextMonth').disabled=selected>=end;document.querySelectorAll('.year-labels span').forEach(el=>{const year=Number(el.textContent);el.style.left=(year===2020?0:year===2031?100:monthIndex(year+'-01-01')/129*100)+'%';});const marker=document.getElementById('todayMarker');marker.hidden=now<start||now>end;marker.style.left=Math.max(0,Math.min(100,monthIndex(now)/129*100))+'%';document.getElementById('selectedSituation').textContent='Situación a la fecha seleccionada · '+format(selected);}
 function render(data,state){controls(state);const points=series(data,state),C=RSCharts,W=1100,H=320,left=78,right=25,top=20,bottom=55,iw=W-left-right,ih=H-top-bottom,total=Math.max(1,points[0].total);const stamp=date=>new Date(date+'T12:00:00Z').getTime(),min=stamp(start),max=stamp(end),x=date=>left+(stamp(date)-min)/(max-min)*iw,y=count=>top+ih*(1-count/total);const path=field=>points.map((r,i)=>(i?'L':'M')+x(r.date).toFixed(2)+','+y(r[field]).toFixed(2)).join(' ');let svg='';for(let i=0;i<5;i++){const v=total*i/4,yy=y(v);svg+=`<line x1="${left}" x2="${W-right}" y1="${yy}" y2="${yy}" stroke="#E1E1EC"/><text x="${left-12}" y="${yy+4}" text-anchor="end" fill="#71718E" font-size="11">${C.number(Math.round(v))}</text>`;}
 for(let year=2021;year<=2031;year++){const xx=x(year+'-01-01');svg+=`<text x="${xx}" y="${H-20}" text-anchor="middle" fill="#71718E" font-size="11">${year}</text>`;}
 svg+=`<path d="${path('vig')}" stroke="#2D2D93" stroke-width="3" fill="none"/><path d="${path('cad')}" stroke="#8E91B4" stroke-width="3" fill="none"/>`;
 const selected=state.fechaAnalisis,markerX=Math.max(left,Math.min(W-right,x(selected))),current=RSData.view(data,state).summary;svg+=`<line x1="${markerX}" x2="${markerX}" y1="${top}" y2="${top+ih}" stroke="#1A1A3A" stroke-width="1.5" stroke-dasharray="5 4"/><circle cx="${markerX}" cy="${y(current.vig)}" r="5" fill="#2D2D93" stroke="white" stroke-width="2"/><circle cx="${markerX}" cy="${y(current.cad)}" r="5" fill="#8E91B4" stroke="white" stroke-width="2"/>`;
 points.forEach((r,i)=>{const xx=x(r.date),prev=i?x(points[i-1].date):left,next=i<points.length-1?x(points[i+1].date):W-right;svg+=`<rect data-month="${i}" x="${(prev+xx)/2}" y="${top}" width="${Math.max(1,(next-prev)/2)}" height="${ih}" fill="transparent" tabindex="0" role="button" aria-label="Seleccionar ${format(r.date)}"/>`;});
 const host=document.getElementById('timeChart');host.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="group" aria-label="Vigentes y caducados a cierres mensuales">${svg}</svg>`;
 host.querySelectorAll('[data-month]').forEach(el=>{const r=points[Number(el.dataset.month)],previous=points[Number(el.dataset.month)-1];const detail=`<strong>${format(r.date)}</strong><dl><dt>Vigentes</dt><dd>${C.number(r.vig)}</dd><dt>% Vigencia</dt><dd>${C.pct(r.pctVig)}</dd><dt>Caducados</dt><dd>${C.number(r.cad)}</dd><dt>% Caducidad</dt><dd>${C.pct(r.pctCad)}</dd><dt>Nuevos caducados desde cierre anterior</dt><dd>${previous?C.number(r.cad-previous.cad):'—'}</dd></dl>`;el.onpointermove=e=>C.tooltip(e,detail);el.onpointerleave=C.hide;el.onfocus=()=>{const b=el.getBoundingClientRect();C.tooltip({clientX:b.left,clientY:b.top},detail);};el.onblur=C.hide;el.onclick=()=>RSState.set({fechaAnalisis:r.date});el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();RSState.set({fechaAnalisis:r.date});}};});
 const initialCad=RSData.view(data,{...state,fechaAnalisis:start}).summary.cad;const jumps=points.map((p,i)=>({date:p.date,count:p.cad-(i?points[i-1].cad:initialCad)})).filter(p=>p.date<=state.fechaAnalisis&&p.count>0).sort((a,b)=>b.count-a.count||a.date.localeCompare(b.date)).slice(0,3);const peaks=document.getElementById('expiryPeaks');peaks.textContent='Meses con más núcleos que pasan a caducados: '+(jumps.length?jumps.map(p=>new Intl.DateTimeFormat('es-EC',{month:'short',timeZone:'UTC'}).format(new Date(p.date+'T12:00:00Z')).replace(/\.$/,'')+'. '+p.date.slice(0,4)+': '+C.number(p.count)).join(' · '):'Sin incrementos entre cierres completos para esta selección.');peaks.title='Cierres mensuales completos hasta '+format(state.fechaAnalisis)+'. Conteos del grupo y territorio seleccionados.';}
 root.RSTemporal={today,format,start,end,close,monthIndex,move,build,series,init,render};
})(globalThis);
